source "https://rubygems.org"
# gemspec

gem "algorithms"
gem "ansi_palette", "~> 0.0.1"
gem "chroma-db"
gem "cli-ui", "~> 2.2"
gem "color", "~> 1.8"
gem "dotenv", "~> 3.1"
gem "engtagger"
gem "groq"
gem "highline", "~> 3.0"
gem "jongleur"
gem "json"
gem "jsonl"
gem "kramdown", "~> 2.4"
gem "langchainrb", "~> 0.14.0"
gem "lingua"
gem "mimemagic", "~> 0.4.3"
gem "minitest", "~> 5.11"
gem "minitest-rg", "~> 5.3"
gem "nano-bots"
gem "natty-ui"
gem "ohm"
gem "ohm-contrib"
gem "open3", "~> 0.2.1"
gem "open4", "~> 1.3"
gem "paint", "~> 2.3"
gem "parallel", "~> 1.25"
gem "pastel", "~> 0.8.0"
gem "pdf-reader", "~> 2.12"
gem "pg"
gem "pgvector"
gem "polyglot", "~> 0.3.5"
gem "pragmatic_segmenter"
gem "pragmatic_tokenizer"
gem "pry", "~> 0.14.2"
gem "pry-doc", "~> 1.5"
gem "pry-stack_explorer", "~> 0.6.1"
gem "rake", "~> 13.0"
gem "rb-readline", "~> 0.5.5"
gem "redis", "~> 5.2"
gem "rubocop", "~> 1.64"
gem "rubocop-minitest", "0.35.1"
gem "rubocop-packaging", "0.5.2"
gem "rubocop-performance", "1.21.1"
gem "rubocop-rake", "0.6.0"
gem "ruby-lsp", "~> 0.18.4"
gem "ruby-spacy"
gem "scalpel"
gem "sequel"
gem "shale", "~> 1.1"
gem "solargraph"
gem "stream_lines"
gem "thor", "~> 1.2"
gem "timeout", "~> 0.4.1"
gem "tomoto"
gem "tool_tailor", "~> 0.2.1"
gem "treetop"
gem "tty-box", "~> 0.7.0"
gem "tty-markdown", "~> 0.7.2"
gem "tty-prompt"
gem "tty-screen", "~> 0.8.2"
gem "tty-spinner", "~> 0.9.3"
gem "tty-table", "~> 0.12.0"
gem "wordnet"
gem "wordnet-defaultdb"
gem "yaml"
