source "https://rubygems.org"
# gemspec

gem "algorithms"
gem "ansi_palette"
gem "chroma-db"
gem "cli-ui"
gem "color"
gem "dotenv"
gem "engtagger"
gem "ffi"
gem "groq"
gem "highline"
gem "jongleur"
gem "json"
gem "jsonl"
gem "kramdown"
gem "langchainrb"
gem "lingua"
gem "mimemagic"
gem "minitest"
gem "minitest-rg"
gem "nano-bots"
gem "natty-ui"
gem "ohm"
gem "ohm-contrib"
gem "open3"
gem "open4"
gem "paint"
gem "parallel"
gem "pastel"
gem "pdf-reader"
gem "pg"
gem "pgvector"
gem "polyglot"
gem "pragmatic_segmenter"
gem "pragmatic_tokenizer"
gem "pry"
gem "pry-doc"
gem "pry-stack_explorer"
gem "rake"
gem "rb-readline"
gem "redis"
gem "rubocop"
gem "rubocop-minitest"
gem "rubocop-packaging"
gem "rubocop-performance"
gem "rubocop-rake"
gem "ruby-lsp"
gem "ruby-spacy"
gem "scalpel"
gem "sequel"
gem "shale"
gem "stream_lines"
gem "thor"
gem "timeout"
gem "tomoto"
gem "tool_tailor"
gem "treetop"
gem "tty-box"
gem "tty-markdown"
gem "tty-prompt"
gem "tty-screen"
gem "tty-spinner"
gem "tty-table"
gem "wordnet"
gem "wordnet-defaultdb"
gem "yaml"

gem "down", "~> 5.4"

gem "zip", "~> 2.0"

gem "wav-file", "~> 0.0.3"
