services:
  flowise:
    image: flowiseai/flowise
    container_name: flowise
    restart: unless-stopped
    environment:
      - PORT=3002
      - DATABASE_PATH=/root/.flowise
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - LOG_PATH=/root/.flowise/logs
      - DEBUG=True
      - LOG_LEVEL=debug
    ports:
      - "3002:3002"
    volumes:
      - ./data/flowise:/root/.flowise
      - ./data/flowise/output:/data/output
    entrypoint: /bin/sh -c "sleep 3; flowise start"
    networks:
      - flowbots
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./data/redis/data:/data
    ports:
      - "6379:6379"
      - "8081:8081"
      - "8001:8001"
    networks:
      - flowbots
  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: flowbots
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgvector/local-data:/data
      - ./data/pgvector/pgdata:/var/lib/postgresql/data
    networks:
      - flowbots
  langfuse-server:
    image: ghcr.io/langfuse/langfuse:latest
    restart: unless-stopped
    depends_on:
      - flowise
      - pgvector
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@pgvector:5432/flowbots
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - NEXT_PUBLIC_SIGN_UP_DISABLED=${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
    networks:
      - flowbots

networks:
  flowbots:
    driver: bridge
